# Generated by Django 2.2.5 on 2020-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pict',
            field=models.ImageField(blank=True, default='default', upload_to='profile_piccs'),
        ),
    ]
