# Generated by Django 2.2.5 on 2020-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poste_By_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Docment_By_Admin',
            field=models.FileField(blank=True, null=True, upload_to='file_Off_Adminstration/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_Off_Adminstration/'),
        ),
    ]
